%% Post-Processing: Bayesian & Permutation Results Aggregation
% =========================================================================
% This script collects the results generated by Step 1.
% It extracts: R-values, Permutation P-values, MSE, MSE P-values, 
% and Bayesian Evidence (BF10, Credible Intervals).
% Output: A single CSV file for reporting.
% =========================================================================

clear; close all; clc;

% --- 1. Define Paths (Same as Step 1) ---
main_path = '/data/home/EEG001/Longitudinal/datafromMac/'; 
result_plot = '/data/home/EEG001/Longitudinal/ForPlot/';
folders = {'csd', 'norm'};
opname = {'preLooPERM2idx_BFedge2', 'FzCPMPERM2idx_BFedge2'}; 

% Output Directory for the Report
report_dir = fullfile(result_plot, 'Bayesian_Validation_Report');
if ~exist(report_dir, 'dir'), mkdir(report_dir); end

SummaryData = {}; 
row_cnt = 1;

fprintf('Starting Data Aggregation...\n');
fprintf('Looking for files in: %s\n', fullfile(result_plot, 'result'));

%% Main Loop
for dd = 1:length(folders)
    for o = 1:length(opname)
        
        % Construct path to result folder
        res_path = fullfile(result_plot, 'result', folders{dd}, opname{o});
        
        % Get all .mat files
        file_list = dir(fullfile(res_path, '*.mat'));
        
        if isempty(file_list)
            fprintf('  No files found in %s\n', res_path);
            continue;
        end
        
        fprintf('  Processing %d files in %s/%s...\n', length(file_list), folders{dd}, opname{o});
        
        for k = 1:length(file_list)
            fname = file_list(k).name;
            full_fname = fullfile(res_path, fname);
            
            try
                tmp = load(full_fname);
                if ~isfield(tmp, 'Extractedge_perm'), continue; end
                
                D = tmp.Extractedge_perm;
                behav_names = fieldnames(D);
                
                % Parse Filename for Metadata (e.g., area_alpha_2017_...)
                parts = strsplit(fname, '_');
                % Assuming format: Data_Freq_Year_Pthresh_...
                % Adjust indices based on your exact filename structure if needed
                % Typically: parts{1}=Data, parts{2}=Freq, parts{3}=Year
                data_type = parts{1}; 
                freq_band = parts{2};
                year_val = parts{3};
                thresh_val = parts{4};
                % parts{4} = Threshold (e.g., '0.05')
                
                for b = 1:length(behav_names)
                    beh_name = behav_names{b};
                    cell_d = D.(beh_name);
                    
                    % Check if Bayesian data exists (Index 42)
                    % Also check if we have the new indices (up to 43)
                    if length(cell_d) >= 42 && ~isempty(cell_d{42})
                        
                        % --- 1. Identify Model Type ---
                        model_type = cell_d{43}; % 'pos', 'neg', 'glm'
                        
                        % --- 2. Extract Metrics based on Model Type ---
                        % Note: 
                        % P-val (R): 1=Pos, 2=Neg, 3=Glm
                        % MSE (True): 14=Pos, 15=Neg, 16=Glm
                        % R (True): 20=Pos, 21=Neg, 22=Glm  <-- NEW
                        % P-val (MSE): 35=Pos, 36=Neg, 37=Glm
                        
                        r_val = nan; 
                        p_r = nan;
                        mse_val = nan; 
                        p_mse = nan;
                        
                        if strcmpi(model_type, 'pos')
                            p_r = cell_d{1};
                            mse_val = cell_d{14};
                            if length(cell_d)>=20, r_val = cell_d{20}; end
                            if length(cell_d)>=35, p_mse = cell_d{35}; end
                            
                        elseif strcmpi(model_type, 'neg')
                            p_r = cell_d{2};
                            mse_val = cell_d{15};
                            if length(cell_d)>=21, r_val = cell_d{21}; end
                            if length(cell_d)>=36, p_mse = cell_d{36}; end
                            
                        elseif strcmpi(model_type, 'glm')
                            p_r = cell_d{3};
                            mse_val = cell_d{16};
                            if length(cell_d)>=22, r_val = cell_d{22}; end
                            if length(cell_d)>=37, p_mse = cell_d{37}; end
                        end
                        
                        % --- 3. Process Bayesian Data ---
                        bayes_res = cell_d{42};
                        trace = bayes_res.mcmc_trace(:, 2); % Slope is col 2
                        
                        slope_mean = mean(trace);
                        ci = quantile(trace, [0.025, 0.975]);
                        
                        % Calculate BF10
                        [bf10, ev_str] = calc_bf10(trace);
                        
                        % --- 4. Store in Summary Data ---
                        SummaryData(row_cnt, :) = { ...
                            folders{dd}, ...        % Folder (csd/norm)
                            opname{o}, ...          % Condition
                            year_val, ...           % Year
                            freq_band, ...          % Frequency
                            thresh_val, ...
                            beh_name, ...           % Behavior (SDS/SAS)
                            model_type, ...         % Model (pos/neg/glm)
                            r_val, ...              % R Value (True)
                            p_r, ...                % R P-value (Perm)
                            mse_val, ...            % MSE Value (True)
                            p_mse, ...              % MSE P-value (Perm)
                            slope_mean, ...         % Bayesian Slope Mean
                            sprintf('[%.2f, %.2f]', ci(1), ci(2)), ... % 95% CI
                            bf10, ...               % Bayes Factor
                            ev_str ...              % Evidence Level
                            };
                        
                        row_cnt = row_cnt + 1;
                    end
                end
                
            catch ME
                fprintf('  Error reading file %s: %s\n', fname, ME.message);
            end
        end
    end
end

%% Save to CSV
if ~isempty(SummaryData)
    % Define Column Names
    VarNames = {'Folder', 'Condition', 'Year', 'Freq', 'P_Thresh','Behavior', 'Model', ...
        'R_True', 'P_Perm_R', 'MSE_True', 'P_Perm_MSE', ...
        'Slope_Mean', 'Slope_95CI', 'BF10', 'Evidence'};
    
    % Create Table
    T = cell2table(SummaryData, 'VariableNames', VarNames);
    
    % Sort by BF10 (Descend) and Year
    try
        % Create a sortable numeric BF column for sorting
        BF_Num = T.BF10;
        BF_Num(isinf(BF_Num)) = 999999; % Treat Inf as huge number for sorting
        [~, idx] = sort(BF_Num, 'descend');
        T = T(idx, :);
    catch
        % Fallback if sorting fails
    end
    
    % Sort table for better readability (e.g., by BF10 descending)
    % T = sortrows(T, 'BF10', 'descend'); 
    
    % Write
    output_csv = fullfile(report_dir, 'BF_results_v2.csv');
    writetable(T, output_csv);
    
    fprintf('\n----------------------------------------------------------\n');
    fprintf('Analysis Finished.\n');
    fprintf('Final Results saved to:\n%s\n', output_csv);
    
    % Preview top results
    disp('Top 5 Strongest Results (based on BF10):');
%     [~, sort_idx] = sort(cell2mat(SummaryData(:, 13)), 'descend'); % Sort by BF10
    disp(T(1:min(5, end), {'Year','Freq','P_Thresh','Behavior','Model','R_True','P_Perm_R','BF10'}));
    
else
    fprintf('No results extracted. Check if Step 1 generated the .mat files correctly.\n');
end


%% Helper Function: Calculate Bayes Factor (Savage-Dickey)
function [bf, ev] = calc_bf10(trace)
    % 1. Estimate Posterior Density at 0
    [f, xi] = ksdensity(trace);
    post_at_0 = interp1(xi, f, 0, 'linear', 0);
    
    % 2. Define Prior Density at 0 (Standard Cauchy ~ 0.707)
    prior_scale = 0.707;
    prior_at_0 = 1 / (pi * prior_scale * (1 + (0/prior_scale)^2)); % Cauchy PDF at x=0
    
    % 3. Calculate Ratio
    if post_at_0 < eps
        bf = Inf; % If posterior at 0 is effectively 0, BF is infinite
    else
        bf = prior_at_0 / post_at_0;
    end
    
    % 4. Evidence String
    if bf < 1/3, ev='Favors Null';
    elseif bf < 1, ev='Anecdotal Null';
    elseif bf < 3, ev='Anecdotal';
    elseif bf < 10, ev='Moderate';
    elseif bf < 30, ev='Strong';
    elseif bf < 100, ev='Very Strong';
    else, ev='Extreme';
    end
end